### ISSUE TITLE
Bug: Imported extensions will overwrite existing values

### ISSUE THREAD

**Issue by downsider** [lexide/syringe#14]
If we have several imported files that each have extension calls for the same service, only the last call will be included in the final config array

Each call has a numeric key (0, 1, 2, etc...) so when we use array_replace_recursive, the calls in that array are overwritten because they use the same numeric key

for example:
```yaml
# file a.yml
extensions:
  myService:
    - method: foo
```
```yaml
#file b.yml
extensions:
  myService:
    - method: bar
```
```yaml
# file main.yml
imports:
  - a.yml
  - b.yml
```
The resulting config array will only contain the extensions from `b.yml` is it was the last file to be processed (last overwrite wins)
