### ISSUE TITLE
"extends" doesn't respect namespace

### ISSUE THREAD

**Issue by downsider** [lexide/syringe#6]
When extending a n abstract service from a different namespace, any service or parameters references in the abstract definition are not checked for namespace changes.

e.g.

```yml
# namespace "myproject_mylibrary"
subService:
  class: MyProject\SubService

abstractService:
  calls:
    - method: "add"
      arguments: 
        - "@subService"

# namespace "myproject_myapplication"

### This fails with the error "the service 'subService' does not exist"
### The namespace myproject_mylibrary is not prepended to the service name in the extended definition
appService:
  extends: "@myproject_mylibrary.abstractService"
  class: "..."

```
